#!/usr/bin/env node
/**
 * Shared test audit writer — records when tests ran and the outcome.
 * Output: test-audit/last-run.json, test-audit/LAST_RUN.md, test-audit/history.jsonl
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..', '..');
const AUDIT_DIR = path.join(ROOT, 'test-audit');
const MAX_HISTORY = 100;

function gitShortSha() {
  try {
    return execSync('git rev-parse --short HEAD', { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch {
    return null;
  }
}

function parseNodeTestSummary(output) {
  const tests = output.match(/ℹ tests (\d+)/)?.[1];
  const pass = output.match(/ℹ pass (\d+)/)?.[1];
  const fail = output.match(/ℹ fail (\d+)/)?.[1];
  const durationMs = output.match(/ℹ duration_ms ([\d.]+)/)?.[1];
  return {
    tests: tests != null ? Number(tests) : null,
    pass: pass != null ? Number(pass) : null,
    fail: fail != null ? Number(fail) : null,
    durationMs: durationMs != null ? Number(durationMs) : null,
  };
}

function writeAudit(record) {
  fs.mkdirSync(AUDIT_DIR, { recursive: true });

  const payload = {
    ...record,
    recordedAt: new Date().toISOString(),
  };

  fs.writeFileSync(
    path.join(AUDIT_DIR, 'last-run.json'),
    `${JSON.stringify(payload, null, 2)}\n`,
  );

  if (record.suite === 'unit') {
    fs.writeFileSync(
      path.join(AUDIT_DIR, 'last-unit.json'),
      `${JSON.stringify(payload, null, 2)}\n`,
    );
  }

  if (record.suite === 'full') {
    fs.writeFileSync(
      path.join(AUDIT_DIR, 'last-full.json'),
      `${JSON.stringify(payload, null, 2)}\n`,
    );
  }

  const historyPath = path.join(AUDIT_DIR, 'history.jsonl');
  fs.appendFileSync(historyPath, `${JSON.stringify(payload)}\n`);

  try {
    const lines = fs.readFileSync(historyPath, 'utf8').trim().split('\n').filter(Boolean);
    if (lines.length > MAX_HISTORY) {
      fs.writeFileSync(historyPath, `${lines.slice(-MAX_HISTORY).join('\n')}\n`);
    }
  } catch {
    /* non-fatal */
  }

  const status = payload.passed ? 'PASSED' : 'FAILED';
  const summary = payload.nodeTest
    ? `${payload.nodeTest.pass ?? '?'} pass, ${payload.nodeTest.fail ?? '?'} fail (${payload.nodeTest.tests ?? '?'} tests)`
    : (payload.smokeSkipped ? 'smoke skipped (no Chromium)' : 'see command output');

  const md = `# Test audit — last run

| Field | Value |
|-------|-------|
| **Status** | ${status} |
| **Suite** | ${payload.suite} |
| **Command** | \`${payload.command}\` |
| **When (UTC)** | ${payload.recordedAt} |
| **Duration** | ${payload.durationMs != null ? `${payload.durationMs} ms` : '—'} |
| **Summary** | ${summary} |
| **Git commit** | ${payload.gitCommit ?? '—'} |
| **Host** | ${payload.hostname} |

${payload.passed ? 'All checks completed successfully.' : 'One or more checks failed — re-run the command above for details.'}

_Auto-generated by \`scripts/test/audit.js\`. See \`knowledge_base/core/TESTING.md\`._
`;

  fs.writeFileSync(path.join(AUDIT_DIR, 'LAST_RUN.md'), md);
}

module.exports = {
  writeAudit,
  parseNodeTestSummary,
  gitShortSha,
  AUDIT_DIR,
  ROOT,
};
